### PR TITLE
build fix: using npm@4.6.1

### PR DESCRIPTION
**Pull request by kubiko**
fixing snap craft build for version 0.24
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

### CODE REVIEW

**Comment by kubiko** [comment]
@xet7 
I created in launchpad wekan project and wekan team where you should be admin and contributor. Feel free to add other people on the list.
Wekan project has wekan-snap repo mirrored from github one:
[https://code.launchpad.net/~wekan-team/wekan/+git/wekan-snap]
sync happens every ~5 hours
There is snap package enabled for this repo which has automatic build upon change in repo enabled, you can see there also build queue:
[https://code.launchpad.net/~wekan-team/+snap/wekan-release]
It has also auto push to store enabled, so once built snap is uploaded to candidate channel.
Once you snap is uploaded you should see it here:
[https://dashboard.snapcraft.io/dev/snaps/7867]
I will need your email from launchpad account so I can add you to snap collaborator list, so you can control promotion to stable channel once candidate version is tested. You can see there some other interesting stats about snap adoption.
For the future once you make change in wekan-snap build and upload should happen automatically, no need for additional interaction.
Next thing would be to move people from wekan-ondra to wekan, not quite sure how to announce this though….. From stats I can see there are ~320 downloads/installs of version 0.23.

I will create also pull request to wekan repo, which will enable continuous integration from master, typically this would be pushing builds to edge channel, from where you can do testing, or more adventures users can use edge channel to track your master branch….

And last thing, if you are interested Ubuntu can do jointed marketing release about wekan snap availability….

kiitos and have a good Juhannus ;)

**Comment by xet7** [comment]
@kubiko 

My launchpad email address can be seen at https://github.com/xet7

Yes you can add pull requests to Wekan for continuous integration.

Yes Ubuntu can do jointed marketing release about wekan snap availability.

Thanks!

**Comment by xet7** [comment]
@kubiko 

I was able to download snap from this page:
https://code.launchpad.net/~wekan-team/+snap/wekan-release/+build/49657

It seems that this page says access denied for me:
https://dashboard.snapcraft.io/dev/snaps/7867

**Comment by xet7** [comment]
Ok snaps work for me now, I was able to publish new ones.

**Pull request merged**
